name: CraftersConquest
version: 1.0.0
author: Sqi
main: com.craftersconquest.core.ConquestCore
api-version: 1.14
softdepend: [Vault, Multiverse-Core, Essentials, SlimeWorldManager, LuckPerms]
commands:
  ccadmingenerate:
    description: "Generates custom items."
    permission:  com.craftersconquest.admin
  ccitemgive:
    description: "Gives a custom item."
    permission:  com.craftersconquest.admin
  accept:
    description: "Accepts a pending request."
    permission:  com.craftersconquest.player
  decline:
    description: "Declines a pending request."
    permission:  com.craftersconquest.player
  region:
    description: "Region configuration commands."
    permission:  com.craftersconquest.admin