name: CraftersConquest
version: 1.0.0
author: Sqi
main: com.craftersconquest.core.ConquestCore
api-version: 1.14
softdepend: [Vault, Multiverse-Core, Essentials]
commands:
  ccadmingenerate:
    description: "Generates custom items."
    permission:  com.craftersconquest.admin